### ISSUE TITLE
Error: Cannot find module './node_modules/polymer-analyzer/lib/analyzer'

### ISSUE THREAD

**Issue by robharting** [samccone/webcomponent-bundle-analyzer#4]
after installed this component globally is get this error when running my equvalant of:
webcomponent-bundle-analyzer {path_to_elements_root_directory} {root_element_list.html} > size-map.html

I get the error:
module.js:549
    throw err;
    ^

Error: Cannot find module './node_modules/polymer-analyzer/lib/analyzer'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Workspace\nodejs\node_modules\webcomponent-bundle-analyzer\analyze.js:13:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

Do you recognize this?

**Comment by samccone** [comment]
Hmm I do not :/ looks like something has changed with how polymer-analyzer bundles itself now which will require some fixing.
